### ISSUE TITLE
Atlantis multiple requests problem

### ISSUE THREAD

**Issue by ttuygun** [ProxymanApp/atlantis#102]
There is no problem when we connect over proxy with Proxyman but when I inspects requests with Atlantis, I can see multiple requests problem.

**Comment by NghiaTranUIT** [comment]
Can you elaborate on what "request problem" is?

Does it means:
- You get a bunch of SSL Error requests?
- Could not see any traffic or anything else?
- You test with iOS Simulator or iOS physical device?

--------------------
From what you mention `connect over proxy with Proxyman but when I inspect requests with Atlantis `, it seems that you set the HTTP Proxy (from iOS devices) to Proxyman, then used it with Atlantis.

I'd say that it's not how it works.

If you use Atlantis, you don't need to set the HTTP Proxy on Wifi anymore. After you config:

```swift
Atlantis.start()
```
It'd automatically connect to Proxyman.

Hence, please try again without setting the HTTP Proxy.

**Comment by ttuygun** [comment]
Multiple requests mean I can see GET, POST or any other requests recursively for same requests.
Connections over Atlantis:
Request 1
Request 1
Request 1
Request 2
Request 2

Connection over proxy:
Request 1
Request 2

There is no problem with connection over proxy.
1. There is no error on requests.
2. Yes, I can see lots of duplicated 200 status coded same requests 
3. It's on iPad physical device

**Comment by NghiaTranUIT** [comment]
Thanks. Can you clarify what iOS, Atlantis, and Proxyman versions you're using?

I guess that you're using the latest build?
- iOS 15.5
- Proxyman 3.5.2
- Atlantis 1.17.0

**Comment by ttuygun** [comment]
> Thanks. Can you clarify what iOS, Atlantis, and Proxyman versions you're using?
> 
> I guess that you're using the latest build?
> 
>     * iOS 15.5
> 
>     * Proxyman 3.5.2
> 
>     * Atlantis 1.17.0

Right, all the latest except iOS 15.4.1

**Comment by ttuygun** [comment]
> Thanks. Can you clarify what iOS, Atlantis, and Proxyman versions you're using?
> 
> I guess that you're using the latest build?
> 
>     * iOS 15.5
> 
>     * Proxyman 3.5.2
> 
>     * Atlantis 1.17.0

Problem can reproducable? Can I need to send logs?

**Comment by NghiaTranUIT** [comment]
@ttuygun if you don't mind, please check out the latest Atlantis 1.20.0.

We've fixed some duplicated connections -> Show the same request twice 👍

**Comment by ttuygun** [comment]
It seems fixed thanks
