### ISSUE TITLE
Unable to build on Xcode 14.0.0 beta

### ISSUE THREAD

**Issue by JohnnyTseng** [ProxymanApp/atlantis#104]
![Screen Shot 2022-06-09 at 11 19 39](https://user-images.githubusercontent.com/2656519/172757072-e05e2d32-83c5-46bb-ba5e-b541f3eb9851.png)
![Screen Shot 2022-06-09 at 11 19 45](https://user-images.githubusercontent.com/2656519/172757078-57c40519-c480-4745-8131-a4c9a619ea6c.png)

Am finding a way to fix this issue, will share if there is any solution!

**Comment by esteluk** [comment]
You've closed the issue - did you identify a fix for this?

**Comment by leondeng** [comment]
Weird, I'm still blocked by this issue with Xcode 14.1...

**Comment by NghiaTranUIT** [comment]
@leondeng can you clone the Repo and try to run it again?

I'm able to successfully run/integrate Atlantis on Xcode 14.1

![Screenshot_2022-11-20_at_14_05_15](https://user-images.githubusercontent.com/5878421/202890180-94ac5b69-3f16-4489-800b-acd60fe93e88.jpg)

**Comment by NghiaTranUIT** [comment]
@leondeng with the latest Atlantis 1.20.0, we completely remove the NSURLConnection, so these errors (the first screenshot) is gone.

**Comment by leondeng** [comment]
Hi @NghiaTranUIT, the errors are from atlantis-proxyman 1.12.0
Do I still need Atlantis as dependency package after adding `pod 'atlantis-proxyman'` in the Podfile?

**Comment by leondeng** [comment]
still the same error after adding Atlantis 1.20.0 to Pods/atlantis-proxyman...

**Comment by NghiaTranUIT** [comment]
@leondeng can you share with me a screenshot? 

The issue was about "NSURLConnection", which is completely removed from Atlantis 1.20.0.

**Comment by leondeng** [comment]
Found it!
ios deployment target of the build target was 12.4, which restricted the version of atlantis-proxyman at 1.12.0 always
changed it to 13.0, pod install fetched 1.20.0 for me!
All good now, except that we are using pusher-js, not pusher swift, so still no possible to check out wss traffic via proxyman.

Thanks anyways, @NghiaTranUIT.

**Comment by NghiaTranUIT** [comment]
Thanks for letting me know 👍  Only WS traffic, which is called from URLSessionWebSocketTask is supported.
