### ISSUE TITLE
Carthage can't build 1.18.2

### ISSUE THREAD

**Issue by ttuygun** [ProxymanApp/atlantis#112]
I successfully build with 1.18.1 but 1.18.2 can't build with carthage

Console:
xcodebuild timed out while trying to read Atlantis-Example-App.xcodeproj 😭

carthage 0.38.0 (installed with brew to m1 mac)
macOS 12.4
Xcode 13.4.1
Xcode build version: Xcode 13.4.1 Build version 13F100
Command:  carthage update --use-xcframeworks --cache-builds

**Comment by NghiaTranUIT** [comment]
I'm not sure what happened, but I'm able to integrate Atlantis 1.18.1 with Atlantis 🤔 

<img width="889" alt="Screen Shot 2022-07-31 at 17 54 01" src="https://user-images.githubusercontent.com/5878421/182022771-c70aeddb-2e3e-4a49-8489-454025f4e917.png">

----------
Maybe you should remove the `--cache-builds`

**Comment by ttuygun** [comment]
OK, I solved it. No specific problem in the tag

**Comment by JohnnyTseng** [comment]
@ttuygun Can you share how did you solve it?

**Comment by NghiaTranUIT** [comment]
@JohnnyTseng just use the latest version. Can you share with me the error log when integrating via Carthage?

**Comment by JohnnyTseng** [comment]
@NghiaTranUIT I'm using the latest version `1.18.2`, the log appears the same as @ttuygun 
so strange

![Screen Shot 2022-09-05 at 14 55 40](https://user-images.githubusercontent.com/2656519/188383666-53055a9e-750d-4f46-8e3f-fe294bd187db.png)


- Xcode 13.4.1
- Carthage 0.38.0

**Comment by JohnnyTseng** [comment]
I found similar issues, wondering if it's the same issue cc @NghiaTranUIT 
https://github.com/realm/realm-swift/issues/6549

**Comment by NghiaTranUIT** [comment]
Can you try to use `carthage update --use-xcframeworks`. It works fine with Xcode 13.4.1 and iOS 15.5.

<img width="874" alt="Screen Shot 2022-09-05 at 14 04 25" src="https://user-images.githubusercontent.com/5878421/188384986-ee7829e7-6c38-4692-8073-998e30934294.png">

**Comment by JohnnyTseng** [comment]
It seems like my network today is too slow to fetch the `Alamofire` dependency 
After manually open the `Atlantis-Example-App` to let Xcode resolve the package first, and run carthage command again, it works.

I think is same issue as https://github.com/realm/realm-swift/issues/6549#issuecomment-640674684 encountered 

Thank you @NghiaTranUIT , solved temporarily!
