### ISSUE TITLE
Connection reset by peer immediately after connection

### ISSUE THREAD

**Issue by vdka** [ProxymanApp/atlantis#115]
When using Proxyman on my mac, Atlantis on my physical device (same network), connection succeeds, but then immediately disconnects with `ECONNRESET` from posix
```
[Atlantis] Found Proxyman with HostName = vdka.local.
[Atlantis] ✅ Connect to vdka.local.
Connection preparing
Connection established
Connection to server failed, error=POSIXErrorCode(rawValue: 54): Connection reset by peer
```

**Comment by vdka** [comment]
I updated my `Info.plist` and noticed Xcode shifted `NSLocalNetworkUsageDescription` into the Xcode project build settings **Info.plist Values** section ... this seemed to break things, once I moved it back info `Info.plist` things work again.

**Comment by NghiaTranUIT** [comment]
Thanks for letting me know 👍
