### ISSUE TITLE
Could not find module 'Atlantis' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator

### ISSUE THREAD

**Issue by ptrkstr** [ProxymanApp/atlantis#117]
I'm trying to import Atlantis into my project but getting the error:
```
Could not find module 'Atlantis' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/.../Index.noindex/Build/Products/Debug-iphonesimulator/Atlantis.swiftmodule
```
I am integrating this using SPM in a project that also contains Cocoapods.
- M1 Pro
- Atlantis 1.18.2
- Xcode Version 14.1 (14B47b)
- Building for simulator iPhone 14 Pro 16.0

**Comment by NghiaTranUIT** [comment]
Hey, just wondering: what iOS version and Xcode you're using?

**Comment by ptrkstr** [comment]
Just updated post with those details @NghiaTranUIT

**Comment by ptrkstr** [comment]
Hey @NghiaTranUIT sorry you are right, it's a problem with my project setup. Will close, thank you for looking into this regardless 🙏
