### ISSUE TITLE
Crash When Intercepting URLSessionUploadTask

### ISSUE THREAD

**Issue by VaslD** [ProxymanApp/atlantis#132]
We recently encountered an Atlantis-related crash at:

https://github.com/ProxymanApp/atlantis/blob/f6f7be1330bd4f847b6d52278acd88516eaac471/Sources/NetworkInjector%2BURLSession.swift#L294-L298

<img width="1440" alt="Screenshot 07-20 15 17 02@2x" src="https://github.com/ProxymanApp/atlantis/assets/3415065/1abbff36-3ffb-4934-b10b-548cf3f1d558">

I've found the cause but since I'm too familiar with method swizzling and calling conventions, I think you might want to take a look and verify this.

The problem is that [`uploadTaskWithRequest:fromData:completionHandler:`](https://developer.apple.com/documentation/foundation/nsurlsession/1411518-uploadtaskwithrequest?language=objc), and its Swift counterpart [`uploadTask(with:from:completionHandler:)`](https://developer.apple.com/documentation/foundation/urlsession/1411518-uploadtask), has an optional `Data?` parameter. Atlantis swizzled this method with a C function `@convention(c) (AnyObject, Selector, AnyObject, AnyObject, AnyObject) -> AnyObject` that marks all parameters non-null.

A third-party library actually passes `nil` to the `Data?` parameter, which causes Atlantis to crash when reading `data`. Although the code uses `if let`, `data` is always implicitly unwrapped to non-optional first because the C function signature declares `AnyObject` (instead of `AnyObject?`).

<img width="1426" alt="Screenshot 07-20 15 35 06@2x" src="https://github.com/ProxymanApp/atlantis/assets/3415065/901f486e-aaca-41be-b5d0-8405b0ba4bf0">

The fix seems to work when declaring parameters for `data` and `completionHandler` as optionals, and taking non-null `data` out of assertions. **As a precaution, you should review other swizzled `URLSessionTask` factory methods to avoid implicit unwraps.**

**Comment by NghiaTranUIT** [comment]
@VaslD can you verify what iOS version you're using?

**Comment by VaslD** [comment]
I have confirmed crash reports from iOS 15.7.2 and 15.1, with IPAs generated from Xcode 14.2 and 14.3.1. Suspicious crashes do happen on other iOS versions during QA but I have not received crash reports to corroborate those claims.

But seeing the latest API documentation (I referenced in the original post) does declare the `data` parameter as nullable, it would be safe to not assume that it isn't.
