### ISSUE TITLE
Xcode 15: The request of a upload task should not contain a body or a body stream

### ISSUE THREAD

**Issue by brandonskane** [ProxymanApp/atlantis#135]
Xcode 15 gives the below warning when running Atlantis, line 325 in `_swizzleURLSessionUploadFromDataWithCompleteHandlerSelector`

```The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.```

<img width="1475" alt="CleanShot 2023-08-22 at 16 27 03@2x" src="https://github.com/ProxymanApp/atlantis/assets/375155/991b4521-81ac-4d99-813f-12862d6537b8">

**Comment by NghiaTranUIT** [comment]
Thanks. Let me investigate it with Xcode 15 Beta

**Comment by NghiaTranUIT** [comment]
I'm unable to reproduce this issue:
- Xcode 15 Beta 7
- iOS 17 Beta
- Use `URLSession.shared.uploadTask(with: request, from: data)`
- the latest Atlantis version.

and I don't get the warning.

![CleanShot 2023-08-23 at 15 00 54@2x](https://github.com/ProxymanApp/atlantis/assets/5878421/81834c3b-7910-44d2-9207-b87f1a5d07f4)

----------
Just wondering: 
1. What iOS version you're using with Xcode 15?
2. When you get the warning, can you help me to trace back (by setting the Breakpoint) what the URLSession's method is called?

thanks in advance 👍

**Comment by yjdv** [comment]
I've got the same issue with lates Xcode 15 RC and Atlantis installed as SPM

**Comment by brandonskane** [comment]
I've tracked it down to NewRelic. When I disable NewRelic from starting, I do not get this error. 

So Xcode 15 + NewRelic + Atlantis causes this to appear. 

Your original stack trace request
![CleanShot 2023-09-18 at 16 27 37@2x](https://github.com/ProxymanApp/atlantis/assets/375155/d6a6776c-112f-465b-b450-71a48d94d52e)

**Comment by yjdv** [comment]
that should be the case I've got new relic too in the project but I can't disable it

**Comment by brandonskane** [comment]
> that should be the case I've got new relic too in the project but I can't disable it

I cannot _disable_ it either, however, in Production since one would not have Atlantis enabled, this is less of a concern, at least to me. It would still be nice to not have this warning during development.

**Comment by yjdv** [comment]
yeah agree on that. it could stay open but with less priority @NghiaTranUIT

**Comment by NghiaTranUIT** [comment]
Thanks. Let me investigate Atlantis and New Relic 👍

**Comment by NghiaTranUIT** [comment]
@yjdv @brandonskane it seems this warning is not from Atlantis. It's from the NewRelic (See the screenshot)

### How to reproduce
1. Setup Xcode 15 + iOS 16
2. Create new empty iOS project 
3. Add New Relic library -> Get the same warning even though there is no Atlantis framework here.

![CleanShot 2023-09-19 at 10 38 50@2x](https://github.com/ProxymanApp/atlantis/assets/5878421/e209e9bc-a45a-43f5-b7f9-33d6c596b668)
