### ISSUE TITLE
Crashes when integrated with Intercom SDK in the same project

### ISSUE THREAD

**Issue by lexrus** [ProxymanApp/atlantis#148]
Thank you for providing this repository, it greatly facilitates our network request testing. Recently I need to use the service of Intercom. When Atlantis and Intercom SDK are used in the project at the same time, I always encounter this crash, so I have to stop using Altantis. The attachment is an empty project that only installed Atlantis and Intercom SDK, and it can stably reproduce this crash.

<img width="1754" alt="Screenshot 2024-06-14 at 9 56 38 AM" src="https://github.com/ProxymanApp/atlantis/assets/219689/1fedfaab-d502-4f1b-a6aa-d1acb1a69db4">

[TestIntercom.zip](https://github.com/user-attachments/files/15830654/TestIntercom.zip)

**Comment by NghiaTranUIT** [comment]
@lexrus you can disable the Websocket Intercept to prevent the crash 👍  

Ref: https://github.com/ProxymanApp/atlantis/issues/134#issuecomment-1803057604

**Comment by lexrus** [comment]
Thank you for your rapid reply. It works.
