### ISSUE TITLE
Is it possible to allow installing atlantis on < iOS 12?

### ISSUE THREAD

**Issue by JohnnyTseng** [ProxymanApp/atlantis#30]
Thanks for developing atlantis, however our project's deployment version is still iOS 11.
Is it possible to allow installing atlantis on < iOS 12? 
Without functioning on older version is okay but only allow it to install (Maybe adding some `#available` flags?) on projects that deployment version are still on older versions

**Comment by NghiaTranUIT** [comment]
Look like it’s possible because NSNetService and URLSessionStreamData both support iOS 11 👍

I will check out and support tomorrow if it’s possible

**Comment by NghiaTranUIT** [comment]
@JohnnyTseng can you try this on your iOS 11 😄 

```
pod 'atlantis-proxyman', :git => 'https://github.com/ProxymanApp/atlantis.git', :branch => 'support-ios-11'
``

I'm downloading the iOS 11 Simulator, but it might take a long time.

**Comment by NghiaTranUIT** [comment]
hey @JohnnyTseng , this PR #31 is done.

Please installing:
```
pod 'atlantis-proxyman', :git => 'https://github.com/ProxymanApp/atlantis.git', :branch => 'support-ios-11'
```
it should work 👍

**Comment by JohnnyTseng** [comment]
That's fast!! Thank you!
