### ISSUE TITLE
Question: Response duration is always empty

### ISSUE THREAD

**Issue by advantis** [ProxymanApp/atlantis#35]
Just noticed that (unlike the proxy approach) all the requests captured using Atlantis have no duration:

![Screen Shot 2020-11-05 at 13 37 42](https://user-images.githubusercontent.com/853858/98237085-07f00980-1f6d-11eb-83e4-253c06f3f566.png)

The [screenshot](https://user-images.githubusercontent.com/853858/98237327-6917dd00-1f6d-11eb-9c06-a36fd5d28238.png) in the [integration doc](https://docs.proxyman.io/atlantis/atlantis-for-ios) shows the same behavior, although this not mentioned explicitly neither in the doc nor in Readme.

So the question is: is this a bug, a missing (yet) feature, or this behavior is intended by design?

**Comment by NghiaTranUIT** [comment]
Hm, good eye. It's a bug. 

I should show the duration. Let me fix it 👍

**Comment by NghiaTranUIT** [comment]
Please check out this beta 🙌 : https://proxyman.s3.us-east-2.amazonaws.com/beta/Proxyman_2.11.1_Missing_Duration_Atlantis.dmg

<img width="1792" alt="Screen Shot 2020-11-05 at 20 34 12" src="https://user-images.githubusercontent.com/5878421/98247801-ac427200-1fa6-11eb-849c-53070584f8d0.png">

**Comment by advantis** [comment]
Wow, you're super fast! Indeed, now duration values show up. Thanks!
