### ISSUE TITLE
[SwiftPM] How to include in only certain configurations?

### ISSUE THREAD

**Issue by jsorge** [ProxymanApp/atlantis#38]
First: this is awesome. I've just installed the Swift Package into our project and it's fantastic!

I'm wondering if there's a way for me to only include the library in a certain configuration (debug in my case) since I would prefer to exclude Atlantis from all of my release builds. Were this just a library in my project I could use a build setting in the `OTHER_LDFLAGS` for my debug configuration to link it. I don't see any way to do this in the Xcode UI though 😞 

Any tips to get this done are much appreciated!

**Comment by NghiaTranUIT** [comment]
You can exclude it in two way:

### Soft approach
It means that you still include Atlantis library to your source code, but don't import it or start the Atlantis. It just stays there and does nothing.

```swift
#if DEBUG
import Atlantis
Atlantis.start()
#endif
```

### Hard approach
It means that you **completely exclude** Atlantis from Production build, but include in Debug build.

1. Duplicate your current target and add suffix "-Production"
2. Select the new target and Remove Atlantis library from the "Framework, libraries, and embedded contents" section

<img width="1411" alt="Screen_Shot_2020-11-12_at_09_06_37" src="https://user-images.githubusercontent.com/5878421/98886775-3dde4200-24c7-11eb-8249-93ab14c3d94b.png">

3. Create a new Scheme that links to the new target. e.g MyApp-Production
4. Use the same code

```swift
#if DEBUG
import Atlantis
Atlantis.start()
#endif
```

5. When you release a Production build, make sure you select MyApp-Production Scheme and achieve it.

**Comment by jsorge** [comment]
Gotcha, thanks!
