### ISSUE TITLE
Failing to capture request body

### ISSUE THREAD

**Issue by hpinhal** [ProxymanApp/atlantis#44]
I'm trying to replace the proxy setup with Atlantis but it's not capturing most of the request bodies.
Doing the same request over and over again, it was only the request body for a couple of them.

![image](https://user-images.githubusercontent.com/2880250/100736053-1eea1600-33ca-11eb-9528-145d4b35aa78.png)

Using the latest version via SPM.
Running on a physical device with iOS 14.2.1.

**Comment by NghiaTranUIT** [comment]
Thanks for the report @hpinhal 👍 

Just wondering that can you see the Response Body? 

and what Networking library that you're using? (e.g Alamofire, AFNetworking or URLSession, or anything else) 🤔

**Comment by NghiaTranUIT** [comment]
Look like I'm able to reproduce the bug. I'm fixing now 🙌

**Comment by NghiaTranUIT** [comment]
Hi @hpinhal 

We've fixed the bug and release Atlantis 1.4.3 (https://github.com/ProxymanApp/atlantis/releases/tag/1.4.3)

Please update your latest version with SPM and try again 🎉

**Comment by hpinhal** [comment]
Hi @NghiaTranUIT ,

Works like a charm. Much appreciated!
