### ISSUE TITLE
app crash if we download big (>300 MB) file

### ISSUE THREAD

**Issue by jsyrtsov** [ProxymanApp/atlantis#57]
please add any comments here if you need more information about this issue
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/58340627/107487753-8d500f00-6b97-11eb-9b80-522967e04aab.png">

**Comment by NghiaTranUIT** [comment]
Sorry to hear that but I'm not sure why NetServiceTransort is not capable of sending your big file.

I suppose that I should have a save check to skip big files, such as over 100Mb to prevent the app crashes 👍

**Comment by jsyrtsov** [comment]
@NghiaTranUIT  thank you for fast answer!

**Comment by NghiaTranUIT** [comment]
@jsyrtsov if you don't mind, please use this pod:

```
pod 'atlantis-proxyman', :git => 'https://github.com/ProxymanApp/atlantis.git', :branch => 'bug/crash-big-files'
```

and share with me whether or not it fixes the crash 😄 

Thank you in advance 👍

**Comment by jsyrtsov** [comment]
@NghiaTranUIT give me few minutes

**Comment by jsyrtsov** [comment]
@NghiaTranUIT 
I've tested with 100 Mb limit, got crash. 50 Mb limit crashed too. 20 Mb limit crashed too, I have assumption that buffer is not clearing, what do you think about it ?

**Comment by NghiaTranUIT** [comment]
Thanks for getting back. Let me check the root of the problem 👍

**Comment by NghiaTranUIT** [comment]
I'm not sure but I could transfer 50Mb by Atlantis to Proxyman macOS.

<img width="1497" alt="Screen_Shot_2021-02-10_at_19_53_54" src="https://user-images.githubusercontent.com/5878421/107512777-e04ab600-6bd9-11eb-981b-686b8aa51284.png">

However, it crashes when I tried a file 150Mb 😿 Google show that there is no memory left, so it crashes the app.

@jsyrtsov:
1. Which iPhone model are you using? I'm iPhone XR iOS 14
2. Do you have a link of the 20Mb file that I can test on my machine?

**Comment by jsyrtsov** [comment]
@NghiaTranUIT 
I'm running on iPhone 7 iOS 13.7 and iOS 14.4 (both of these devices are crashing. I did't try to repeat crash on any simulator, should I?
I'm downloading two big files at the same time (~30MB + ~200MB + ~300MB. it is catalog DataBases) and Atlantis is trying to send it to Proxyman almost simultaneously and got crash on second file.
I can try to find some links with big files if you need it.
Also I can just exclude domain with catalogs from Transporting to Atlantis.
Thnx in advance.

**Comment by NghiaTranUIT** [comment]
Yes, please try on the Simulator too, since there is plenty of RAM. Try on 20Mb and 100Mb.

> Also I can just exclude domain with catalogs from Transporting to Atlantis.

Good idea. I might support the Exclusive List 😄

**Comment by jsyrtsov** [comment]
Okay, I'll try on simulator without limit and with different limits

**Comment by NghiaTranUIT** [comment]
Look like I found the problem @jsyrtsov The bug is from JSONEncoder, not the URLStreamTask.

Since the file size is large, it might not be able to represent in the JSON Format. I'm looking for a solution to exclude in this case

**Comment by jsyrtsov** [comment]
oh, good news!

**Comment by NghiaTranUIT** [comment]
@jsyrtsov let check the latest commit from `bug/crash-big-files` branch 👍 

I decide to skip the large body if it exceeds the threshold (100Mb)

<img width="1605" alt="Screen_Shot_2021-02-10_at_20_44_52" src="https://user-images.githubusercontent.com/5878421/107517954-032c9880-6be1-11eb-8a8c-7fab59b6cb86.png">

**Comment by jsyrtsov** [comment]
I've got crash with 100MB limit and with 50MB limit. With 25MB limit everything is OK)

**Comment by jsyrtsov** [comment]
I've tested on simulator and didn't get any crashes. But on iPhone 7 I don't get crash only if I set 25MB limit.

**Comment by NghiaTranUIT** [comment]
Thanks. I would like to limit the big file size to 50Mb. iPhone 7 lacks available RAM, so it might be crashed
