### ISSUE TITLE
Missing release notes for v1.8.0

### ISSUE THREAD

**Issue by justin** [ProxymanApp/atlantis#63]
Hi, I saw that the 1.8.0 release was pushed yesterday. Is it possible to ensure that release notes are added to those releases? Given the nature of what Atlantis does its helpful to be able to distribute that as a link to our team. 

https://github.com/ProxymanApp/atlantis/releases/tag/1.8.0

**Comment by NghiaTranUIT** [comment]
Thanks. I'm updating the release note now 👍

**Comment by NghiaTranUIT** [comment]
I've updated the release note. Thank you for raising the ticket @justin 🎉

**Comment by justin** [comment]
Thank you, @NghiaTranUIT!
