### ISSUE TITLE
Atlantis not connecting to Proxyman

### ISSUE THREAD

**Issue by shgew** [ProxymanApp/atlantis#69]
My Mac and iPhone are connected to the same network and are connected by a USB cable.
However, when launching an app with Atlantis inside, it is unable to find Proxyman in the network, even if I specify hostname. It connects successfully only if I:
1. Launch the app for the first time. Atlantis successfully connects upon giving local network permission.
2. I put the app to background for a second or longer. Atlantis successfully connects upon reopening the app.

The issue was not present about 2 months ago, when I last used this awesome tool!

**Comment by shgew** [comment]
I have no issues with simulator though.

**Comment by NghiaTranUIT** [comment]
Not sure what might cause the connection problem 🤔 

@shgew if it works 2 months ago, can you try to install the old release https://github.com/ProxymanApp/atlantis/releases

**Comment by shgew** [comment]
Will do! I will post the result here.

**Comment by shgew** [comment]
Installing versions 1.7.0 and 1.5.0 didn't help :\
However, relaunching Proxyman also results in immediately established connection, in addition to the two points above.
Maybe it has something to do with either macOS or iOS updates in the last two months?

**Comment by NghiaTranUIT** [comment]
From what I remember, I haven't changed any major things regarding the Bonjour Service since the first build. I will investigate the bug 👍

**Comment by shgew** [comment]
Thank you!

**Comment by ski081** [comment]
Hi. I'm having the same issue, except I cannot get a connection to work at all. I see the following logs when my app startup from Xcode:

---------- 🧊 Atlantis is running (version 1.0)
---------- Github: https://github.com/ProxymanApp/atlantis
---------------------------------------------------------------------------------
[Atlantis] Looking for Proxyman app in the network...
[Atlantis] Found Proxyman with HostName = mstruzin-3e807.local.
[Atlantis] ✅ Connect to mstruzin-3e807.local.
[Atlantis] Flush 1 items

But then I don't get the Atlantis group in the Proxyman sidebar when I start using network connections. I have tried via `start()` and `start(hostName:)` and get the same result for both.

**Comment by NghiaTranUIT** [comment]
@ski081 please update your Atlantis to the latest [version 1.9.0](https://github.com/ProxymanApp/atlantis/releases/tag/1.9.0) to make it works with the latest version of Proxyman 2.24.0

There is a major update regarding the Bonjour Service since version 1.0 👍

**Comment by ski081** [comment]
Hi.

I installed via Swift Package Manager, and the version shows as 1.9.0 in Xcode. Although the console printout shows 1.0. Should I try to install via CocoaPods instead?

**Comment by NghiaTranUIT** [comment]
Look like it's a bug when installing via SPM (not show the version correctly).

Regarding why you could not connect to Proxyman, there are many reasons and one of them is the cooperated network might block Bonjour Service. Therefore, Atlantis could not discover and connect to Proxyman.

Please try running on your simulator, and see if you can see the traffic @ski081

**Comment by NghiaTranUIT** [comment]
I tested via CocoaPod
- Able to see the traffic from iOS Simulators
- Unable to see the traffic at my cooperated wifi (it blocks Bonjour Service)
- but I'm able to see the traffic at my home Wifi.

**Comment by ski081** [comment]
Hi @NghiaTranUIT. I am seeing the same. When on my corporate VPN, I cannot see traffic from the device, even when it is connected via a cable. It will discover the running instance of Proxyman on my Mac, but will not capture traffic.

Do you know if there is any way around this? Or would I need to start working with my support team to unblock incoming traffic for specific ports?

**Comment by NghiaTranUIT** [comment]
@ski081 can you try to disable all VPN apps from your macOS and iOS device 🤔 

For Bonjour Service, Proxyman opens port 10909. Please check with your security team if they block it 👍

**Comment by shgew** [comment]
Would like to mention that the issue is extremely rare after the v1.9.0. It happened only one or two times after the update. Thank you for the fix!
