### ISSUE TITLE
Atlantis uses huge amounts of memory if Proxyman isn't running

### ISSUE THREAD

**Issue by mluisbrown** [ProxymanApp/atlantis#74]
We have Atlantis in our app, and the app receives a *lot* of web socket messages. If Proxyman isn't running, all these messages (and any other network requests) get appended to `pendingPackages` here: https://github.com/ProxymanApp/atlantis/blob/main/Sources/Transporter.swift#L95

There seems to be no limit on the size of this array, so this will continue until the app runs out of memory, or Proxyman is launched.

It would be great to have an option to disable the storing of pending packages, so if you don't have Proxyman running, these packages are just lost, and you only start seeing new data in Proxyman from the moment you start it.

**Comment by NghiaTranUIT** [comment]
It's a good point 👍 

I suppose that I will add a limit (50 items at max or Receiving the Memory Warning), then it will release all pending data.

Let me fix it 💯

**Comment by NghiaTranUIT** [comment]
Just a friendly reminder that this issue is fixed and released. Please check it out 😄 @mluisbrown

**Comment by mluisbrown** [comment]
Thank you so much for the amazingly fast turnaround 🙏
