### ISSUE TITLE
Swift gRPC plugin for protoc

### ISSUE THREAD

**Issue by r-plus** [ProxymanApp/atlantis#98]
We should write all of the `YourClientInterceptorFactoryProtocol` protocol defined methods for gRPC like this.

```
public class AtlantisInterceptorFactory: MyClientInterceptorFactoryProtocol {
    public func makeAInterceptors() -> [ClientInterceptor<ARequest, AResponse>] {
        [AtlantisInterceptor()]
    }
    public func makeBInterceptors() -> [ClientInterceptor<BRequest, BResponse>] {
        [AtlantisInterceptor()]
    }
    public func makeCInterceptors() -> [ClientInterceptor<CRequest, CResponse>] {
        [AtlantisInterceptor()]
    }
    ...
```

It would be nice if it could be generated automatically by grpc plugin including AtlantisInterceptor implementation that wrote on README to reduce the hassle like [swift-grpc plugin](https://github.com/grpc/grpc-swift/tree/main/Sources/protoc-gen-grpc-swift).

**Comment by NghiaTranUIT** [comment]
Thanks but I'm not sure how to tackle this.

**Comment by r-plus** [comment]
In past, I thought creating protoc plugin for this purpose is good idea.
But now I'm thinking creating plugin plan that generated code will completely depend on grpc-swift's protoc-gen-grpc-swift is not good for Atlantis.

Thanks.
I'll open issue when I got more good robust idea.
