### ISSUE TITLE
Atlantis.start() produces EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by valentinperignon** [ProxymanApp/atlantis#99]
With Atlantis 1.16.0 and Xcode 13.3.1, running Atlantis.start() sometimes produces a EXC_BAD_ACCESS error (in NetworkInjector:injectAllURLConnection() function).
The error does not occur with Xcode 13.3.0.

**Comment by NghiaTranUIT** [comment]
I'd like to reproduce it:

1. Which iOS version are you using? 
2. Does it happen on iOS Simulator or Physical devices?

**Comment by valentinperignon** [comment]
1. We are using iOS 15.4
2. It happens in both iOS Simulator and Physical devices (tested on iPhone 13 Pro)

**Comment by NghiaTranUIT** [comment]
Thanks. I'm checking out tonight 👍

**Comment by NghiaTranUIT** [comment]
@valentinperignon if you don't mind, when the exception occurs on `NetworkInjector:injectAllURLConnection` please share with me the screenshot that shows the number of lines 👍 

I'd like to investigate it since I'm unable to reproduce it.

**Comment by NghiaTranUIT** [comment]
Hey @valentinperignon let's try this branch:

### Changelog
- I decide to remove all legacy support (In this case, it's NSURLConnection). It's where your crash occurs.

### How to install
#### Cocoapod
```
pod 'atlantis-proxyman', :git => 'https://github.com/ProxymanApp/atlantis.git', :commit => '379e15a9a24856fee583135d353326fbed2960ca'
```

### SPM
- Checkout this commit: `379e15a9a24856fee583135d353326fbed2960ca`

---------------------
Let me know if it works for you 👍

**Comment by valentinperignon** [comment]
After several tests, the app doesn't seem to crash anymore 🥳

**Comment by NghiaTranUIT** [comment]
Just a friendly reminder that I've released Atlantis 1.17.0. It fixes the bug 🐛

**Comment by NghiaTranUIT** [comment]
@Blyabtroi does it often happen or rarely?

**Comment by Blyabtroi** [comment]
It started rarely, but now it happens every time.

**Comment by NghiaTranUIT** [comment]
Tried to reproduce but not luck @Blyabtroi. Just wondering: Does it your 3rd-party library? It looks like it's a Analytic library.

![230920330-16132c6e-f1dc-4c28-b3ec-f55480422a8c](https://user-images.githubusercontent.com/5878421/231642142-9c8a8538-474b-4832-8b3f-48cd2e60397a.jpg)

**Comment by Blyabtroi** [comment]
@NghiaTranUIT yes, it's FirebasePerformance
